### ISSUE TITLE
Consider adding chainId to actionId computation

### ISSUE THREAD

**Issue by EndymionJkb** [balancer/balancer-v3-monorepo#106]
We're going to keep the same Authorizer for V3 (with an open question of whether it's literally the same instance, or just the same code).

Another question is whether we want to make actionIds more granular by including the chainId. It wouldn't change anything with the authorizer itself, which just operates on opaque bytes32 actionIds.

**Comment by joaobrunoah** [comment]
Hey @EndymionJkb , do we still need this issue? I mean, Weighted and Stable factories are deployed, and we're computing actionIds the same way as before.

**Comment by EndymionJkb** [comment]
Apparently we considered and rejected it, so I guess not.
