### ISSUE TITLE
Review balances rounding direction

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#152]
After #141 and #83 we have scaling factors moved to the vault, with rounding directions for amounts given, calculated, and balances.

For amounts given and calculated it's rather straightforward to reason about it.
For balances, at least using weighted pool math the rounding direction does not produce consistent results (both for swaps and for join-exit math). See e.g. https://github.com/balancer/balancer-v3-monorepo/actions/runs/6857314725/job/18646175815.

It might be the case that the rounding direction won't make any difference given the precision loss for the weighted math. Review together with #49.

**Comment by EndymionJkb** [comment]
This has been addressed in multiple PRs since this time. Rounding directions are even more important than we originally thought; we have to introduce them to the pool invariant and rate calculations. I'd say the "balances" part has been addressed, though.
