### ISSUE TITLE
Consider switching to PRB (or Solady) math

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#157]
The math library landscape changed a lot since V2 launch, and there might be better alternatives out there.

https://github.com/PaulRBerg/prb-math is getting a lot of traction lately.

Might help e.g. with #152, where our current math library seems to be introducing non-linear behavior at the edges where there is some precision loss.

**Comment by EndymionJkb** [comment]
Turns out our library is actually one of the better ones; not clear we could improve on it. And ran out of time in any case.
