### ISSUE TITLE
Review unsafe casts

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#181]
See comments in Vault regarding casts in events:
```
// TODO No they aren't anymore (stored as uint112)! Review this.
```

**Comment by EndymionJkb** [comment]
Comments are no longer there, and we nearly always use SafeCast now anyway with anything that has user input. There is an "unsafeCast" function we use, but that is working with max uint128 balances going to uint256. I did find one place where we were casting a timestamp without checking. (We do it in tests, but that's fine.)
