### ISSUE TITLE
Review liquidity approximation tests (weighted pool)

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#325]
There are some intermittent failures; see [here](https://github.com/balancer/balancer-v3-monorepo/actions/runs/8056042012/job/22004275372?pr=324) for a sample.

**Comment by elshan-eth** [comment]
We have not used roundingDelta in assertLiquidityOperationNoSwapFee. This [pr](https://github.com/balancer/balancer-v3-monorepo/blob/48df908d3febf8c7c71fb5c2b00f27b259cdd783/pkg/vault/test/foundry/LiquidityApproximation.t.sol#L697
) has fixed it.
