### ISSUE TITLE
Test: extreme drain with flashloaned BPT

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#360]
Suppose you have a version of bb-a-usd (pool A: boosted dai / usdc / usdt), and pair that against wstETH (pool B: bb-a-usd / wstETH).

`bb-a-usd` can be flashloaned from pool B and used to exit pool A. In the worst case, all of the BPT supply of pool A is paired in pool B. Technically you wouldn't be able to exit all of the supply because of the absolute minimum limit, but we can still test for corner cases that may arise from this situation.

**Comment by EndymionJkb** [comment]
Resolved by #846, etc.
