### ISSUE TITLE
Tolerance issue in `LiquidityApproximationTest`

### ISSUE THREAD

**Issue by wei3erHase** [balancer/balancer-v3-monorepo#376]
On attaching another case scenario to the same expectations ( #372 ) we discovered that the test is giving false positives when the pool returns `~0` "dynamic" fee, despite the expectations being run with a fuzzed `swapPercentageFee`. 

The test reasoning is the following, a pool with `dynamicFee = poolConfig.staticSwapFeePercentage` should pass all the same expectations as a static fee pool in LiquidityApproximationTest. Yet when modifying it to `dynamicFee = 0`, tests pass all the same.

`roundingDelta` and `swapFeePercentageDelta` seem to be too permissive on this test, at least for the fee percentages covered (0-10%), but:
- `roundingDelta` could be reduced to `1e10` and tests will still pass.
- `swapFeePercentageDelta` could be reduced from 20% to 7% and tests will still pass.
- when reducing both Deltas, **dynamic test (returning 0 fee) still pass**.

**Comment by jubeira** [comment]
We've been bashing liquidity approximation tests quite a bit since this.
