### ISSUE TITLE
Address Mutation testing findings

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#459]
Results [here](https://docs.google.com/spreadsheets/d/1q3Qh052nIyELNB4OkiDIqb_mNRobgxzTcZqNc2FRGgc/edit#gid=1381122675) for commit `68c116c6a6889d7bebbb0e84e1205485b2e146ae`.

The target contracts are only the vault and its extensions. Some mutation types don't really matter that much, but we can definitely improve our tests by coding tests that kill some of the mutants.

**Comment by EndymionJkb** [comment]
Resolved by #859 and others.
