### ISSUE TITLE
idea: Interchangeable query mode

### ISSUE THREAD

**Issue by wei3erHase** [balancer/balancer-v3-monorepo#491]
The current queryMode relies now in 2 conditions, `vaultState.isQueryDisabled` and `EVMCallModeHelpers.isStaticCall()` (which checks `tx.origin == 0`, as proof of static call). The reason for `isQueryDisabled` is that, on a shady EVM in which `tx.origin` could in fact be `address(0)`, it can be disabled to avoid rugs.

Query mode is not even testable in foundry, since mocking the `tx.origin` is tricky, then it creates the must of having Hardhat tests (which imo, should not be there and save us hrs of compiling + running tests).

The idea I've got is: just one more proxy implementation bro, one more..
`Vault -> Extension -> Admin -> ActivateQueryMode`

Why? because we don't care about the gas consumption of activating `vaultState.isQueryEnabled`.
```solidity
contract ActivateQueryMode {
   function queryMode() external onlyVault {
        require(tx.origin == 0);
        vaultState.isQueryEnabled = true;
    }
}
```

In this way, we can replace `ActivateQueryMode` contract with anything, for tests for example, we skip the require, for shady EVMs, we add requirement conditions, we allow this contract to be different from implementation to implementation, w/o having to change the core codebase (or even adding logic to it).

**Comment by jubeira** [comment]
We've been using queries in foundry so far without issues. I don't think it's worth changing the current design at this stage.
