### ISSUE TITLE
Review state update after before hooks

### ISSUE THREAD

**Issue by EndymionJkb** [balancer/balancer-v3-monorepo#500]
What state can before hooks modify? Ensure that anything a hook might modify in a before hook gets updated before calling the main function. During the hooks hackathon, we updated the static swap fee in the pool config - and realized that the pool config was cached (i.e., not updated) after the hook. So, you cannot currently modify the swap fee in a hook.

Maybe this is fine - it would make more sense to use dynamic fees than overwrite and restore the static fee - but we should make these decisions consciously, and document what data is reloaded after before hooks, which constraints what hooks can modify.

**Comment by jubeira** [comment]
@EndymionJkb I think we have no pending feedback to address on this front. WDYT?

**Comment by EndymionJkb** [comment]
> @EndymionJkb I think we have no pending feedback to address on this front. WDYT?

We have no known issues to address; it's just something for auditors, etc. to verify. There is a note about it "Safety of reentrant hooks" in the Auditor's doc.
