### ISSUE TITLE
Batch router: BPT transfers and approvals

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#531]
We're calling `bpt.approve` and `bpt.transfer` in some instances in the batch router. This is kinda inefficient because BPTs are actually facades that call the vault, which in fact calls the extension. So the chain is router --> BPT --> vault --> vault extension.

Can we move the external methods for transfer and approve from the extension to the vault, and then call the vault directly instead of using the BPT facade? In that case, the call chain would be router --> vault.

**Comment by EndymionJkb** [comment]
Is this obsolete now that we have permit2, infinite self-allowance, etc.?
