### ISSUE TITLE
Revisit approach to block wrap/unwrap below a minimum amount

### ISSUE THREAD

**Issue by joaobrunoah** [balancer/balancer-v3-monorepo#564]
In the vault, the function `erc4626BufferWrapOrUnwrap` checks if `amountGivenRaw < _MINIMUM_WRAP_AMOUNT`. However, the given token (in or out) could have any amount of decimals. We need to refactor this code to take decimals into consideration.

**Comment by jubeira** [comment]
For simplicity we've just adjusted the amounts in #944 .
