### ISSUE TITLE
Deterministic pool addresses

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#60]
Pool factories should use CREATE2, so that their address can be calculated before its creation.

The salt should probably include the chain ID and a nonce somewhere to make unique addresses. E.g. `salt = hash(chainId, nonce++);`.

**Comment by EndymionJkb** [comment]
I believe we've decided that this no longer makes sense, given the number of moving parts that would go into determining a pool: type, hook, various flags. We *could* have deterministic addresses for the "vanilla" pools (no hooks, minimal config), but it doesn't seem worth it. Could just introduce an onchain registry at that point.
