### ISSUE TITLE
Consider preventing vault state read when we're outside the pause window

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#648]
If we first check the timestamp, we don't need to read the vault state here: https://github.com/balancer/balancer-v3-monorepo/pull/644/files#diff-b757055907971a411ff87a80666c784ed52f185cd2cf892abbd46bfe9f1cd38dR157

**Comment by EndymionJkb** [comment]
I'm not sure what you mean here. `_isVaultPaused` is an &&, so if we're past the timestamp it will short-circuit and not check the vault state anyway.

**Comment by jubeira** [comment]
Yeah this is correct already.
