### ISSUE TITLE
Query and Actual batch swaps of boosted pools are different sometimes

### ISSUE THREAD

**Issue by joaobrunoah** [balancer/balancer-v3-monorepo#738]
Sometimes, a batch swap query in a boosted pool returns a slightly different result from the actual swap. It happens because the batch swap of a boosted pool is composed of three steps:

* Wrap TokenIn
* Trade wrapped TokenIn by wrapped TokenOut
* Unwrap TokenOut

In the query mode, the first and third steps (wrap/unwrap) are only previews; we don't execute them, so the rate of the wrapped tokens doesn't change. However, the wrap/unwrap is executed in the actual operation so the total supply and total assets of the wrapped tokens change, and it introduces rounding issues in the order of 1 wei to the token rate. This rounding issue propagates to the boosted pool (2nd step) which uses a fixed 18 decimals rate, so it amplifies the error a bit for 18 decimal tokens.

**Comment by jubeira** [comment]
I think this is addressed already right?

There's still a difference that can't really be solved without moving tokens around, but that's expected.

**Comment by joaobrunoah** [comment]
As @jubeira mentioned, this is already addressed. We are returning the preview result, which is as close as we can get from the real operation.

Real operations impact the token rates, and therefore the yield-bearing pool's swap results, and this is not captured by queries. We could make queries capture it, but it'd be more complex to keep the code, so we preferred the simplicity.
