### ISSUE TITLE
BalancerPoolToken::getRate cannot be overridden

### ISSUE THREAD

**Issue by andreiashu** [balancer/balancer-v3-monorepo#866]
Although the documentation alludes to the possibility of this being the case, a pool cannot currently override the `getRate` method in order to implement its own logic for determining the BPT rate. The `virtual` modifier is missing:

https://github.com/balancer/balancer-v3-monorepo/blob/0966a1c80e0ca9622fd1791a5b14b4ac053056aa/pkg/vault/contracts/BalancerPoolToken.sol#L155-L164

**Comment by jubeira** [comment]
Thanks for the observation @andreiashu !
