### ISSUE TITLE
`ProtocolFeeController`: Unable to Change Pool Creator After Pool Registration

### ISSUE THREAD

**Issue by andreiashu** [balancer/balancer-v3-monorepo#872]
The current implementation of the `ProtocolFeeController` contract does not allow changing the pool creator address after a pool has been registered. This limitation poses a problem for custom AMM pool projects built on top of Balancer, such as FXPools.

### Current Behavior

- The pool creator is set during pool registration via the `registerPool` function.
- The pool creator address is stored in the `_poolCreators` mapping.
- There is no mechanism to update this address after registration.

### Desired Behavior

We need the ability to change the pool creator address post-registration. This would allow for scenarios such as:

1. Transferring pool creator rights from an EOA wallet to a smart contract for automated fee management and distribution.
2. Updating pool creator address in case of key rotation or organizational changes.

## Proposed Solution

Consider adding a new function to the `ProtocolFeeController` contract that allows changing the pool creator address. This function should:

1. Be callable only by the current pool creator or a designated admin role.
2. Update the `_poolCreators` mapping with the new address.
3. Emit an event to log the change.

Example function signature:
```solidity
function updatePoolCreator(address pool, address newPoolCreator) external;
```

## Impact

Implementing this feature would allow for more complex and evolving governance structures around pool fee management.

**Comment by EndymionJkb** [comment]
Thanks again for your input!

This was a deliberate choice, though of course we can always revisit decisions. It's the same with all the pool roles: pause manager and swap fee manager. The general idea was that these should probably not be EOAs, but multisig or other contracts where access control would be managed outside Balancer. We don't know how people might want to use it (e.g., give permission to multiple accounts), so we don't impose a particular access control scheme.

The safest way to transfer control outside governance would be a two-step transfer/claim pattern (used in places in v2), where the current permissioned account can set a pending controller address, which then needs to call a "claim" function to complete the transfer.

**Comment by jubeira** [comment]
@andreiashu as pointed out above, the idea was to keep the fee controller simple and let pool creators decide how to handle the role in a layer above. 

Do you think that solution would be viable in your case as opposed to having an `update` function in the fee controller?

**Comment by andreiashu** [comment]
hi @jubeira @EndymionJkb I think that might work for us. I understand your focus here on keeping things simple.
Closing this issue since as you said I think we can manage around this
