### ISSUE TITLE
Consider limiting pool creator fee to 99%

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#887]
Instead of 100%, which would make LP fees 0, it might be a good idea to leave some wiggle room.

**Comment by EndymionJkb** [comment]
Per auditor comment, a 100% fee will cause a division by zero error here. Consider checking for this and providing a custom error message - or, as the name suggests, we could just not allow 100% at all, but set a maximum at a lower value. (That value would be arbitrary, though.)

Vault.sol:
```
locals.swapFeeAmountScaled18 = amountCalculatedScaled18.mulDivUp(
    swapState.swapFeePercentage,
    swapState.swapFeePercentage.complement()
);
```
