### ISSUE TITLE
Investigate vulnerability to double-entry point tokens

### ISSUE THREAD

**Issue by EndymionJkb** [balancer/balancer-v3-monorepo#912]
Per TOB-BALV3-8:

> Some proxied tokens have multiple addresses. If a token with multiple
> addresses is used in the Vault, this token can be drained by calling the settle function since the reserves accounting of the Vault assumes a token only has a single address associated with it.

Celo is such a token. We had a reentrancy issue in v2 with double-entry tokens; is there anything we can do beyond documenting it?

**Comment by jubeira** [comment]
Let's just close this one after this is clearly documented; we won't support these.
