### ISSUE TITLE
Review Weighted Pool fees/guardrails for "near-proportional" unbalanced adds

### ISSUE THREAD

**Issue by EndymionJkb** [balancer/balancer-v3-monorepo#913]
v2 used to calculate the maximum invariant growth (and charge fees) based on the entire amount of liquidity added; in v3, we changed this to only charge fees on the "unbalanced" portion. So, adding very large amounts to a pool with very different weights "almost" proportionally will incur almost no fees. With batch settlement, it's possible to add unbalanced/withdraw proportional at almost no cost.

**Comment by jubeira** [comment]
This has been reviewed. The implicit fee added in #1020 for sensitive pools (e.g. stable with low liquidity) + the rounding direction in `computeInvariant` should do the trick.

Moreover, there's no way to exit in the same tx without paying fees, as add unbalanced + remove proportional is taxed anyways.
