### ISSUE TITLE
Naming / interfacing / misc considerations

### ISSUE THREAD

**Issue by jubeira** [balancer/balancer-v3-monorepo#95]
TODO list, to review after getting the code to a functional state in `main`:
- [ ] `userData` in [regular interfaces](https://github.com/balancer/balancer-v3-monorepo/pull/82/files#r1329195982).
- [ ] Be explicit about the fact that `userData` [is optional](https://github.com/balancer/balancer-v3-monorepo/pull/82/files#r1329645521).
- [ ] [Vault getter](https://github.com/balancer/balancer-v3-monorepo/pull/82/files#r1329199714)
- [ ] Mint / Burn ([ref](https://github.com/balancer/balancer-v3-monorepo/pull/84#discussion_r1334226542))

**Comment by EndymionJkb** [comment]
I believe we've addressed all this things in various PRs.
